### ISSUE TITLE
update for latest bucklescript?

### ISSUE THREAD

**Issue by anabelian** [hiroqn/nix-bucklescript#1]
I tried to get this package working with current BuckleScript, namely by changing the versions to point to BS 6.2.0 and the 4.06.1 version of the vendored OCaml, but camlp4 then fails to build with `ocamlbuild not found`.

According to [this](https://github.com/BuckleScript/ocaml/blob/4.06.1%2BBS/INSTALL.adoc), it seems `ocamlbuild` is now distributed separately, so `bucklescript.nix` will have to be changed to fit.

Removing the `ocamlbuild = ocaml` line makes camlp4 compile, and the build proceeds for a little bit more before `ninja` fails saying `build.ninja` could not be found.

If I drop into a `nix-shell` and use the build instructions on the BS repo [here](https://github.com/BuckleScript/bucklescript/blob/6.2.0/CONTRIBUTING.md) (involving `./scripts/ninja.js`) I can compile the full thing but I don't know how to turn that into a Nix package with all the `$out` stuff.

**Comment by hiroqn** [comment]
Thank you for comment

there are sometimes disruptive changes in BS build . (that is reason for this repository)
and recently i didn't try this repo, sorry.

 but i found my nix code for 5.0.6  at my local computer and push to github (
https://github.com/hiroqn/nix-bucklescript/commit/7aaf7ab6d4344eb0a866e297a7a2e789b58eed8b) perhaps you can refer it

 i may try to fix this this weekend, if possible

**Comment by anabelian** [comment]
Thank you for your help :)

**Comment by anabelian** [comment]
Here is what I have: https://github.com/anabelian/nix-bucklescript/commit/ac51642c491db890a7986efab89d4079c22d7bdb

It builds fine but after creating a new project with `bsb init`, `npm run build` fails with an `ENOENT` saying it could not find `ninja`. If I change the `installPhase` to `node $out/scripts/install.js` then the build fails because `./configure.py` could not be found (even though when I execute the whole script manually in a `nix-shell`, the `install.js` script runs fine).

**Comment by anabelian** [comment]
All right, I think I've got it working in https://github.com/anabelian/nix-bucklescript/commit/b9a29e4588bc403d684d0ba5d6d141858e67f9f4.

**Comment by hiroqn** [comment]
https://github.com/anabelian/nix-bucklescript/commit/b9a29e4588bc403d684d0ba5d6d141858e67f9f4 is very helpful, thanks.

i cherry-pick your commit into this pr  (https://github.com/hiroqn/nix-bucklescript/pull/3/files), and change some build and works well
